"use client";
import { useState } from "react";
import Link from "next/link";
import { IconMail, IconPhone, IconBrandWhatsapp, IconMapPin, IconLoader2 } from "@tabler/icons-react";
import { fetchApi } from "@/lib/utils";
import { PageBreadcrumb } from "@/components/layout/Editorial";
const FAQS = [
  ["How do I place an order?", "Choose your formula and pack size, add it to your cart, and continue to checkout. Prices are in US dollars. Available payment and delivery options are shown at checkout."],
  ["Where can I track my order?", "Sign in and open Orders in your account to see your order status and any tracking details available. If you need help, send us your order number."],
  ["Where can I find ingredient information?", "Open a product page to read its formula and serving details. The ingredient library and MWP University have more information to explore."],
  ["Can I return a product?", "Please read our returns policy for eligibility and instructions. If your order arrives damaged or you receive the wrong item, contact us with your order number and photos."],
  ["Do you deliver to my address?", "Delivery availability, charges, and estimates are confirmed at checkout for your address. Contact our team if you need help before ordering."],
];
export default function ContactPage() {
  const [form, setForm] = useState({ name: "", email: "", phone: "", subject: "General Inquiry", message: "" });
  const [loading, setLoading] = useState(false);
  const [feedback, setFeedback] = useState(null);
  const change = e => { setForm(f => ({ ...f, [e.target.name]: e.target.value })); setFeedback(null); };
  const submit = async e => {
    e.preventDefault(); if (loading) return;
    setLoading(true); setFeedback(null);
    try { const response = await fetchApi("/content/contact", { method: "POST", body: JSON.stringify({ ...form, name: form.name.trim(), email: form.email.trim(), message: form.message.trim() }) }); setFeedback({ success: true, message: response.data?.message || "Your message has been sent. Our team will get back to you by email." }); setForm({ name: "", email: "", phone: "", subject: "General Inquiry", message: "" }); }
    catch (error) { setFeedback({ success: false, message: error.message || "Your message couldn't be sent. Try again or contact us by email." }); }
    finally { setLoading(false); }
  };
  return <div className="mwp-page"><div className="mwp-container"><PageBreadcrumb current="Contact" /><div className="mwp-contact-grid"><section className="mwp-contact-intro"><h1 className="mwp-title">Let&apos;s talk.</h1><p className="mwp-lead">A question about a formula? Need a hand with an order? Choose the way that works for you. We&apos;re here to help.</p><div className="mwp-contact-methods">
    {[{ Icon: IconMail, label: "Email our team", value: "support@mwpsupplements.com", href: "mailto:support@mwpsupplements.com" }, { Icon: IconBrandWhatsapp, label: "Message on WhatsApp", value: "+91 76783 36268", href: "https://wa.me/917678336268" }, { Icon: IconPhone, label: "Call us", value: "+91 76783 36268", href: "tel:+917678336268" }].map(({ Icon, label, value, href }) => <a key={label} className="mwp-contact-method" href={href} {...(href.startsWith("https") ? { target: "_blank", rel: "noopener noreferrer" } : {})}><Icon className="h-5 w-5 shrink-0 text-neutral-500" stroke={1.6} /><div><h2>{label}</h2><p>{value}</p></div></a>)}
    <div className="mwp-contact-method"><IconMapPin className="h-5 w-5 shrink-0 text-neutral-500" stroke={1.6} /><div><h2>Our address</h2><p>132, Ramdaspeth, Nagpur, Maharashtra</p><a className="mwp-text-link mt-2 inline-block" href="https://www.google.com/maps/search/?api=1&query=132+Ramdaspeth+Nagpur+Maharashtra" target="_blank" rel="noopener noreferrer">Get directions</a></div></div></div><p className="mt-7 text-sm leading-relaxed text-neutral-500">For an existing order, include your order number so we can help you faster.</p></section>
    <section className="mwp-contact-form"><h2>Send us a message</h2><p>Tell us what you need. We&apos;ll reply to the email address below.</p><form onSubmit={submit} className="mwp-form-grid"><div><label htmlFor="contact-name" className="mwp-field-label">Full name *</label><input id="contact-name" name="name" autoComplete="name" required maxLength={100} value={form.name} onChange={change} className="mwp-field" placeholder="Your name" /></div><div><label htmlFor="contact-email" className="mwp-field-label">Email address *</label><input id="contact-email" name="email" type="email" autoComplete="email" required maxLength={254} value={form.email} onChange={change} className="mwp-field" placeholder="you@example.com" /></div><div><label htmlFor="contact-phone" className="mwp-field-label">Phone <span className="font-normal text-neutral-500">(optional)</span></label><input id="contact-phone" name="phone" type="tel" autoComplete="tel" maxLength={30} value={form.phone} onChange={change} className="mwp-field" placeholder="Include country code" /></div><div><label htmlFor="contact-subject" className="mwp-field-label">What is it about?</label><select id="contact-subject" name="subject" value={form.subject} onChange={change} className="mwp-field">{["General Inquiry", "Order Status", "Collaboration", "Feedback"].map(s => <option key={s}>{s}</option>)}</select></div><div className="mwp-form-wide"><label htmlFor="contact-message" className="mwp-field-label">Your message *</label><textarea id="contact-message" name="message" rows={5} required maxLength={5000} value={form.message} onChange={change} className="mwp-field resize-y" placeholder="How can we help?" /></div><div className="mwp-form-wide"><button className="mwp-button w-full sm:w-auto" disabled={loading}>{loading && <IconLoader2 className="h-4 w-4 animate-spin" />}{loading ? "Sending…" : "Send message"}</button><p className="mt-4 text-xs leading-relaxed text-neutral-500">Your information is used to respond to this message. <Link className="underline underline-offset-2" href="/privacy-policy">Privacy policy</Link></p></div></form>{feedback && <p role={feedback.success ? "status" : "alert"} className={`mwp-form-feedback ${feedback.success ? "mwp-form-feedback-success" : "mwp-form-feedback-error"}`}>{feedback.message}</p>}</section>
    </div></div><section className="mwp-section bg-[#f6f2eb]"><div className="mwp-container mwp-faq-grid"><div><h2 className="mwp-heading">A few helpful answers.</h2><p className="mwp-lead mt-4">Before you send a message, you might find what you&apos;re looking for here.</p><Link className="mwp-text-link mt-6 inline-block" href="/account/orders">View your orders</Link></div><div>{FAQS.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section></div>;
}
